version: '3.8'

services:
  hushdrop:
    image: hushdrop:pi4
    container_name: hushdrop
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - /DATA/AppData/hushdrop/whisper-models:/root/.cache/whisper
      - /DATA/AppData/hushdrop/uploads:/app/uploads
      - /DATA/AppData/hushdrop/data:/app/data
      - /DATA/AppData/hushdrop/.env:/app/.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s