version: '3.8'

services:
  # Backend-only development service
  backend-dev:
    build:
      context: .
      target: development
    ports:
      - "3001:3001"  # Backend API only
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting container node_modules
      - whisper-models:/root/.cache/whisper  # Cache Whisper models
      - uploads-data:/app/uploads  # Persistent uploads
    environment:
      - NODE_ENV=development
      - PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    env_file:
      - .env
    restart: unless-stopped
    command: ["npm", "run", "dev:server"]  # Only run backend server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Give time for Whisper model download

  # Full development service (frontend + backend in container)
  app-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"  # Frontend (SvelteKit)
      - "3001:3001"  # Backend API
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting container node_modules
      - whisper-models:/root/.cache/whisper  # Cache Whisper models
      - uploads-data:/app/uploads  # Persistent uploads
    environment:
      - NODE_ENV=development
      - PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Give time for Whisper model download

  # Production service
  app:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - whisper-models:/root/.cache/whisper  # Cache Whisper models
      - uploads-data:/app/uploads  # Persistent uploads
    environment:
      - NODE_ENV=production
      - PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  whisper-models:
    driver: local
  uploads-data:
    driver: local